- link:
    ~/.zshrc: shells/zsh/zshrc
    ~/.p10k.zsh: shells/zsh/p10k.zsh
    ~/.zprofile: shells/profile

- shell:
    - command: "[ -x ~/.bin/antibody ] || curl -sfL git.io/antibody | sh -s - -b ~/.bin"
      description: Install antibody
    - command: cd shells/zsh && ~/.bin/antibody bundle < zsh_plugins.txt > zsh_plugins.zsh
      description: Bundle plugins
