" Plugins using vim-plug
" https://github.com/junegunn/vim-plug

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf'
Plug 'w0rp/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-syntastic/syntastic'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
call plug#end()
